# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
# For tabs in the control_sidebar (right screen) add the 'control_sidebar' config key:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md

admin_lte:
    options:
        skin: skin-blue
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: false

    knp_menu:
        enable: false

    routes:
        adminlte_login: admin_fos_user_security_login
        adminlte_login_check: admin_fos_user_security_check
        adminlte_registration: admin_fos_user_registration_register
        adminlte_password_reset: admin_fos_user_resetting_request
        adminlte_welcome: admin_home_index
