fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: admin
    user_class: App\Entity\User
    from_email:
        address: "noreply@myzore.com"
        sender_name: "My Zore"
    