security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PROMOTER:    ROLE_USER
        ROLE_ADMIN:       ROLE_PROMOTER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: admin_fos_user_security_login
                check_path: admin_fos_user_security_check
                failure_path: admin_fos_user_security_login
                default_target_path: admin_home_index

            logout:
                path: admin_fos_user_security_logout
            anonymous:    true
        
        promoter:
            pattern: ^/promotor
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: promoter_fos_user_security_login
                check_path: promoter_fos_user_security_check
                failure_path: promoter_fos_user_security_login
                default_target_path: promoter_home_index

            logout:
                path: promoter_fos_user_security_logout
            anonymous:    true

        site_general:
            pattern: ^/usuario
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: general_fos_user_security_login
                check_path: general_fos_user_security_check
                failure_path: general_fos_user_security_login
                default_target_path: general_fos_user_profile_account

            logout:
                path: general_fos_user_security_logout
            anonymous:    true
        
        site_promoter:
            pattern: ^/\w+/usuario
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: promoter_user_fos_user_security_login
                check_path: promoter_user_fos_user_security_check
                failure_path: promoter_user_fos_user_security_login
                default_target_path: promoter_user_fos_user_profile_account

            logout:
                path: promoter_user_fos_user_security_logout
            anonymous:    true
        
        

    access_control:
        - { path: ^/usuario/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/$, role: ROLE_USER }
        - { path: ^/\w+/usuario/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w+/usuario/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w+/usuario/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w+/usuario/$, role: ROLE_USER }
        - { path: ^/admin/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/$, role: ROLE_ADMIN }
        - { path: ^/promotor/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/promotor/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/promotor/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/promotor/$, role: ROLE_PROMOTER }
