security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_DIRECTOR:    ROLE_USER
        ROLE_ADMIN:       ROLE_DIRECTOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: fos_admin_security_login
                check_path: fos_admin_security_check
                failure_path: fos_admin_security_login
                default_target_path: fos_admin_profile_account

            logout:       true
            anonymous:    true

        public:
            pattern: ^/
            form_login:
                # csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                failure_path: fos_user_security_login
                default_target_path: fos_user_profile_account

            logout:       true
            anonymous:    true
        
        

    access_control:
        - { path: ^/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/ingresar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/restablecer-clave, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/$, role: ROLE_ADMIN }
