kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin:
    resource: '../../src/Controller/Admin'
    type: annotation
    prefix: /admin

promoter:
    resource: '../../src/Controller/Promoter'
    type: annotation
    prefix: /promotor