#Security
fos_user_security_login:
    path:  "/ingresar"
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: "/verificacion"
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: "/salir"
    defaults:  { _controller: FOSUserBundle:Security:logout }

#Profile
fos_user_profile_account:
    path:  "/cuenta"
    defaults:  { _controller: FOSUserBundle:Profile:show }

#fos_user_profile_show:
#    locales:  { en: "/profile", es: "/cuenta" }
#    defaults:  { _controller: FOSUserBundle:Profile:show }

fos_user_profile_edit:
    path: "/cuenta/editar"
    defaults:  { _controller: FOSUserBundle:Profile:edit }

#Registration
fos_user_registration_register:
    path: "/registro"
    # defaults:  { _controller: App\Controller\FOSUserBundle\RegistrationController:register }
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_registration_check_email:
    path: "/registro/verificar-email"
    defaults:  { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path: "/registro/confirmar/{token}"
    defaults:  { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path: "/registro/confirmado"
    defaults:  { _controller:  FOSUserBundle:Registration:confirmed }

#Resetting
fos_user_resetting_request:
    path: "/restablecer-clave/solicitar"
    defaults:  { _controller:  FOSUserBundle:Resetting:request }

fos_user_resetting_send_email:
    path: "/restablecer-clave/enviar-email"
    defaults:  { _controller:  FOSUserBundle:Resetting:sendEmail }

fos_user_resetting_check_email:
    path: "/restablecer-clave/verificar-email"
    defaults:  { _controller:  FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path: "/restablecer-clave/restablecer/{token}"
    defaults:  { _controller:  FOSUserBundle:Resetting:reset }

#ChangePassword
fos_user_change_password:
    path: "/cuenta/cambiar-clave"
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }