#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "./routes/fos_user.yaml"
    prefix: '/usuario'

fos_admin:
    resource: "./routes/fos_admin.yaml"
    prefix: '/admin'
